### ISSUE TITLE
 Fiskaly TSE URL IP addresses

### ISSUE THREAD

**Issue by cgoose1** [fiskaltrust/getting-started#6]
Can you provided all the IP addresses used by Fiskaly TSE URL kassensichv.io? We need all possible IP addresses for our FW rules.

**Comment by TSchmiedlechner** [comment]
Hi @cgoose1,
as far as we know, fiskaly doesn't provide guaranteed static IP addresses for their endpoints, unfortunately. It seems like there's no other way than adding the domain to your firewall.

If this isn't sufficient for you, I'd kindly ask you to [directly contact fiskaly](https://kassensichv.net/kontakt/), thanks!
